apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jkth7svex-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:5f0e1c80abf94f50018f5263d2a875c5f46fec46@sha256:8dabb8cb68939c94254e1b7e9a6712a0221b0589e7d16387e57cfb43d721497c
          name: container-image
