apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jkth7svex-python
  janus-idp.io/tekton: jkth7svex-python
  backstage.io/kubernetes-id: jkth7svex-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jkth7svex-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
