apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jkth7svex-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jkth7svex-python 
  name: jkth7svex-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jkth7svex-python 
